### ISSUE TITLE
No Message Displayed

### ISSUE THREAD

**Issue by ver24436** [TheRealKizu/CustomWhitelistReason#13]
### Issue description

- Expected result: What were you expecting to happen?
Players to be presented with a custom message when they attempt to join the server when it's Whitelisted.

- Actual result: What actually happened?
Players do not see a custom message and stuck in the "Loading Resources" window.

### Steps to reproduce the issue
1. Start PMMP 3.9.5 with whitelist enabled.
2. Attempt to Join the server.
3. Stuck in "Loading Resources" window

### OS and versions
* PocketMine-MP: 3.9.5 for Minecraft: Bedrock Edition v1.12.0 (protocol version 361)
* PHP: 7.2
* Server OS: Microsoft Windows [Version 10.0.18362.10022]
* Game version: Win10 1.12.1

### Plugins
Plugins (1): CustomWhitelistReason v1.0.7

![image](https://user-images.githubusercontent.com/35013625/66861265-913c3480-ef43-11e9-88b3-8804c2384a43.png)

**Comment by TheRealKizu** [comment]
Will be fixed when I have time.

**Comment by TheRealKizu** [comment]
It works for me. 
![Screenshot from 2019-10-28 16-40-35](https://user-images.githubusercontent.com/40911019/67664020-bdbf6a00-f9a1-11e9-8d52-156b2f6c320b.png)

**Comment by TheRealKizu** [comment]
Please conclude your list of plugins by typing /plugins or /pl

**Comment by ver24436** [comment]
[08:18:14] [Server thread/INFO]: Plugins (1): CustomWhitelistReason v1.0.7

As per my original post - the only plugin installed is the CustomWhitelistReason v1.0.7 to ensure there are no conflicts.

![image](https://user-images.githubusercontent.com/35013625/67691536-fd636300-f95b-11e9-88c3-20b63e884037.png)

**Comment by ver24436** [comment]
I have found the issue.  I have completely removed the install of Minecraft Bedrock Edition on Windows 10, and installed a clean copy.  

The problem is now resolved and the plugin is working as expected.  Sorry for the trouble.

**Comment by ver24436** [comment]
I have found what I believe to be the cause of the issue.  As I said above the issue went away when I reinstalled a clean copy of Minecraft Windows 10 Edition.

I discovered that if you 'disabled' "Screen Animations" the problem occurs.  It works fine when it is enabled.

It's not clear if this is something you can fix on the coding side or if it's simply a client bug, but thought you should be aware, should others experience this issue.

**Comment by TheRealKizu** [comment]
It's for the client
